window.SITE_CONFIG = {
  siteTitle: "Sylvia Pothier — Galerie d'art",
  metaDescription: "Découvrez les œuvres originales de Sylvia Pothier, artiste peintre à Clermont-Ferrand. Peinture à l'eau, univers abstrait floral, œuvres originales et commandes sur mesure.",
  artistName: "Sylvia Pothier",
  heroHeading: "Une peinture abstraite florale, entre douceur, lumière et émotion.",
  heroText: "Depuis plus de 20 ans, Sylvia Pothier développe un univers pictural sensible et poétique, où la matière fluide, la couleur et l'inspiration florale se rencontrent dans une écriture contemporaine.",
  location: "Clermont-Ferrand, Puy-de-Dôme",
  shippingShort: "Œuvres originales • expédition soignée • retrait possible",
  shippingLong: "Expédition protégée, retrait à l'atelier ou remise en main propre selon la localisation.",
  commissionsShort: "Commandes sur mesure possibles",
  aboutHeading: "Un univers abstrait floral, délicat et vivant.",
  aboutText1: "Installée à Clermont-Ferrand, Sylvia Pothier peint depuis plus de 20 ans. Son travail s'inscrit dans un univers abstrait floral où la peinture à l'eau laisse émerger des compositions sensibles, lumineuses et profondément émotionnelles.",
  aboutText2: "Chaque œuvre originale cherche un équilibre entre mouvement, transparence, matière et poésie. Sylvia Pothier réalise également des commandes sur mesure pour les collectionneurs, amateurs d'art et intérieurs en quête d'une pièce singulière.",
  email: "contact@artiste.fr",
  instagramHandle: "@sylviapothier",
  instagramUrl: "https://instagram.com/",
  whatsappUrl: "https://wa.me/33000000000",
  featuredArtworkId: "floraison-interieure"
};

window.ARTWORKS = [
  {
    id: "floraison-interieure",
    title: "Floraison intérieure",
    year: 2025,
    category: "Abstrait floral",
    medium: "Peinture à l'eau sur papier",
    size: "80 × 100 cm",
    price: 1250,
    currency: "EUR",
    status: "available",
    image: "images/image1.jpg",
    alt: "Œuvre abstraite florale de Sylvia Pothier aux teintes douces et organiques",
    palette: "rose poudré, beige, terre, lumière diffuse",
    description: "Une composition délicate où la fleur devient sensation, mouvement et présence.",
    descriptionLong: "Cette œuvre explore un langage floral libre et poétique, où les transparences de la peinture à l'eau laissent apparaître une matière sensible et vibrante. Pensée comme une respiration visuelle, elle invite à la contemplation.",
    featured: true,
    stripeUrl: ""
  },
  {
    id: "jardin-suspendu",
    title: "Jardin suspendu",
    year: 2024,
    category: "Abstrait floral",
    medium: "Peinture à l'eau sur papier",
    size: "73 × 92 cm",
    price: 980,
    currency: "EUR",
    status: "available",
    image: "images/image2.jpg",
    alt: "Composition abstraite florale aux nuances végétales et lumineuses",
    palette: "vert sauge, crème, ocre clair, brun doux",
    description: "Une œuvre inspirée du végétal, entre élan organique et douceur silencieuse.",
    descriptionLong: "Jardin suspendu joue sur la fluidité du geste et sur la légèreté de la couleur. L'ensemble évoque un paysage intérieur, floral sans être descriptif, où l'imaginaire du spectateur trouve sa place.",
    featured: true,
    stripeUrl: ""
  },
  {
    id: "lumiere-petale",
    title: "Lumière de pétale",
    year: 2023,
    category: "Abstrait floral",
    medium: "Peinture à l'eau sur papier",
    size: "100 × 100 cm",
    price: 1550,
    currency: "EUR",
    status: "available",
    image: "images/image3.jpg",
    alt: "Grande œuvre poétique abstraite florale dans des tons clairs et chaleureux",
    palette: "ivoire, sable, rose fané, ombres chaudes",
    description: "Un grand format enveloppant, lumineux et poétique, pensé comme une présence douce dans l'espace.",
    descriptionLong: "Cette pièce développe une présence plus ample. Le travail de l'eau et des superpositions crée une profondeur calme, presque méditative, tout en laissant subsister une énergie florale subtile.",
    featured: true,
    stripeUrl: ""
  },
  {
    id: "souffle-botanique",
    title: "Souffle botanique",
    year: 2024,
    category: "Abstrait floral",
    medium: "Peinture à l'eau sur papier",
    size: "65 × 81 cm",
    price: 890,
    currency: "EUR",
    status: "reserved",
    image: "images/image4.jpg",
    alt: "Œuvre abstraite florale contemporaine aux accents botaniques",
    palette: "terre cuite, vert tendre, crème, lumière mate",
    description: "Une pièce intime où le motif floral s'efface au profit d'une sensation organique.",
    descriptionLong: "Souffle botanique appartient à une recherche plus intérieure, où la fleur devient presque trace, souffle, écho. Une œuvre subtile, idéale pour un espace calme et épuré.",
    featured: false,
    stripeUrl: ""
  },
  {
    id: "memoire-des-fleurs",
    title: "Mémoire des fleurs",
    year: 2025,
    category: "Abstrait floral",
    medium: "Peinture à l'eau sur papier",
    size: "50 × 70 cm",
    price: 720,
    currency: "EUR",
    status: "available",
    image: "images/image5.jpg",
    alt: "Petit format abstrait floral élégant et contemporain",
    palette: "beige rosé, blanc cassé, brun léger",
    description: "Un format plus intime, délicat et contemporain, parfait pour un intérieur raffiné.",
    descriptionLong: "Cette œuvre condense l'univers de Sylvia Pothier dans un format plus léger. On y retrouve la transparence de la peinture à l'eau, la douceur de la palette et une présence florale suggérée.",
    featured: false,
    stripeUrl: ""
  },
  {
    id: "eclosion-silencieuse",
    title: "Éclosion silencieuse",
    year: 2022,
    category: "Abstrait floral",
    medium: "Peinture à l'eau sur papier",
    size: "89 × 116 cm",
    price: 1680,
    currency: "EUR",
    status: "available",
    image: "images/image6.jpg",
    alt: "Grande composition abstraite florale douce et texturée",
    palette: "gris chauds, sable, vieux rose, profondeur douce",
    description: "Une œuvre ample et structurée, entre effacement, apparition et vibration florale.",
    descriptionLong: "Dans Éclosion silencieuse, le geste reste léger, mais la composition possède une vraie densité. La peinture à l'eau construit ici un espace de lenteur, de matière et de sensibilité.",
    featured: false,
    stripeUrl: ""
  },
  {
    id: "presence-vegetale",
    title: "Présence végétale",
    year: 2023,
    category: "Abstrait floral",
    medium: "Peinture à l'eau sur papier",
    size: "60 × 60 cm",
    price: 640,
    currency: "EUR",
    status: "sold",
    image: "images/image7.jpg",
    alt: "Œuvre abstraite florale vendue de Sylvia Pothier",
    palette: "tons poudrés, lumière douce, présence feutrée",
    description: "Une pièce plus accessible qui garde toute la poésie et la délicatesse de son univers.",
    descriptionLong: "Afficher aussi quelques œuvres vendues peut être intéressant pour montrer que le travail circule déjà et créer un effet de rareté autour des pièces disponibles.",
    featured: false,
    stripeUrl: ""
  }
];
