window.SITE_CONFIG = {
  siteTitle: "Nom de l'artiste — Galerie d'art",
  metaDescription: "Découvrez les œuvres originales de Nom de l'artiste : peinture contemporaine, séries, formats et achat en ligne.",
  artistName: "Nom de l'artiste",
  heroHeading: "Des œuvres sensibles, lumineuses et profondément vivantes.",
  heroText: "Cette version du site est pensée pour une artiste peintre qui veut montrer ses tableaux avec élégance, raconter sa démarche et vendre ses œuvres sans complexité technique.",
  location: "Lyon, France",
  shippingShort: "Expédition protégée • retrait atelier possible",
  shippingLong: "Expédition protégée, retrait à l'atelier ou remise en main propre selon la localisation.",
  commissionsShort: "Commandes personnalisées possibles",
  aboutHeading: "Un univers pictural entre matière, lumière et émotion.",
  aboutText1: "Présente ici la démarche de l'artiste : ses inspirations, sa technique, les thèmes récurrents, ses formats de prédilection et ce qu'elle cherche à transmettre à travers ses tableaux.",
  aboutText2: "Ajoute aussi les éléments qui rassurent les acheteurs : expositions, ateliers, collections privées, commandes réalisées, ou tout simplement son parcours et sa sensibilité.",
  email: "contact@artiste.fr",
  instagramHandle: "@nomartiste",
  instagramUrl: "https://instagram.com/",
  whatsappUrl: "https://wa.me/33000000000",
  featuredArtworkId: "aube-calme"
};

/*
  COMMENT GÉRER LE SITE
  1) Remplace artistName, email, instagram, ville, textes ci-dessus.
  2) Mets tes vraies images dans /assets/artworks/
  3) Pour chaque œuvre ci-dessous, remplace image, titre, prix, dimensions, description.
  4) Si tu as un lien Stripe Payment Link, colle-le dans stripeUrl.
  5) Si tu n'as pas de lien de paiement, laisse stripeUrl vide : le site proposera une réservation par email.
*/

window.ARTWORKS = [
  {
    id: "aube-calme",
    title: "Aube calme",
    year: 2025,
    category: "Paysages",
    medium: "Acrylique sur toile",
    size: "80 × 100 cm",
    price: 1250,
    currency: "EUR",
    status: "available",
    image: "assets/artworks/oeuvre-1.svg",
    alt: "Peinture abstraite douce aux teintes sable, bleu et ocre",
    palette: "beige bleu ocre lumière",
    description: "Une composition lumineuse qui joue avec les transitions entre silence, matière et horizon.",
    descriptionLong: "Cette œuvre explore l'idée d'un espace suspendu entre ciel et terre. Les couches de matière, les fondus lumineux et la palette sable/bleu créent une présence douce, idéale pour un intérieur apaisé.",
    featured: true,
    stripeUrl: ""
  },
  {
    id: "memoire-doree",
    title: "Mémoire dorée",
    year: 2024,
    category: "Abstractions",
    medium: "Huile et pigments sur toile",
    size: "73 × 92 cm",
    price: 980,
    currency: "EUR",
    status: "available",
    image: "assets/artworks/oeuvre-2.svg",
    alt: "Tableau abstrait avec texture ocre, crème et gris doux",
    palette: "ocre crème gris",
    description: "Une pièce chaleureuse à la texture minérale, pensée pour accrocher la lumière du lieu.",
    descriptionLong: "Entre surface patinée et matière plus dense, cette toile mêle pigments et transparences. Elle convient particulièrement aux espaces épurés cherchant une œuvre discrète mais forte.",
    featured: true,
    stripeUrl: ""
  },
  {
    id: "jardin-interieur",
    title: "Jardin intérieur",
    year: 2025,
    category: "Floraux",
    medium: "Technique mixte sur papier marouflé",
    size: "60 × 80 cm",
    price: 760,
    currency: "EUR",
    status: "reserved",
    image: "assets/artworks/oeuvre-3.svg",
    alt: "Peinture florale contemporaine avec feuillages et verts profonds",
    palette: "vert rose beige végétal",
    description: "Une œuvre plus organique, inspirée d'une végétation rêvée et d'un mouvement libre.",
    descriptionLong: "Le geste y est plus spontané, presque botanique, mais toujours contenu par une composition élégante. Parfaite pour une chambre, un salon ou un bureau vivant.",
    featured: false,
    stripeUrl: ""
  },
  {
    id: "velours-du-soir",
    title: "Velours du soir",
    year: 2023,
    category: "Abstractions",
    medium: "Acrylique sur toile",
    size: "100 × 100 cm",
    price: 1550,
    currency: "EUR",
    status: "available",
    image: "assets/artworks/oeuvre-4.svg",
    alt: "Grand tableau abstrait dans des tons profonds bordeaux, sable et ivoire",
    palette: "bordeaux ivoire sable",
    description: "Un grand format enveloppant, parfait pour une pièce de vie avec du caractère.",
    descriptionLong: "Cette composition plus dense donne un vrai point focal à un intérieur. L'équilibre entre profondeur sombre et respiration claire crée un effet sophistiqué.",
    featured: true,
    stripeUrl: ""
  },
  {
    id: "rivage-lent",
    title: "Rivage lent",
    year: 2022,
    category: "Paysages",
    medium: "Huile sur toile",
    size: "65 × 81 cm",
    price: 890,
    currency: "EUR",
    status: "sold",
    image: "assets/artworks/oeuvre-5.svg",
    alt: "Paysage peint au bord de l'eau dans des tons bleus et sable",
    palette: "bleu beige gris eau",
    description: "Une œuvre vendue, utile pour montrer le parcours de l'artiste et la preuve de ventes passées.",
    descriptionLong: "Garder certaines œuvres vendues sur le site permet aussi de montrer l'univers global de l'artiste, tout en créant de la confiance chez les futurs acheteurs.",
    featured: false,
    stripeUrl: ""
  },
  {
    id: "ligne-de-lumiere",
    title: "Ligne de lumière",
    year: 2025,
    category: "Minimal",
    medium: "Acrylique et encre sur toile",
    size: "50 × 70 cm",
    price: 540,
    currency: "EUR",
    status: "available",
    image: "assets/artworks/oeuvre-6.svg",
    alt: "Œuvre minimaliste contemporaine beige et blanc avec ligne sombre",
    palette: "minimal beige blanc noir",
    description: "Une pièce sobre et contemporaine, idéale pour les intérieurs modernes.",
    descriptionLong: "Le travail du vide, de la ligne et de la respiration visuelle en fait une œuvre très facile à projeter dans un espace design ou minimaliste.",
    featured: false,
    stripeUrl: ""
  },
  {
    id: "terre-rose",
    title: "Terre rose",
    year: 2024,
    category: "Floraux",
    medium: "Technique mixte sur toile",
    size: "90 × 90 cm",
    price: 1120,
    currency: "EUR",
    status: "available",
    image: "assets/artworks/oeuvre-7.svg",
    alt: "Peinture contemporaine rose poudré, terre cuite et crème",
    palette: "rose terre cuite crème",
    description: "Une œuvre douce et affirmée à la fois, entre floral libre et abstraction sensible.",
    descriptionLong: "Les nuances rosées et terre cuite en font une pièce chaleureuse, très appréciée dans un intérieur naturel, boisé ou lumineux.",
    featured: false,
    stripeUrl: ""
  },
  {
    id: "respiration-claire",
    title: "Respiration claire",
    year: 2025,
    category: "Minimal",
    medium: "Pigments et acrylique sur toile",
    size: "40 × 60 cm",
    price: 420,
    currency: "EUR",
    status: "available",
    image: "assets/artworks/oeuvre-8.svg",
    alt: "Petit tableau minimaliste crème, sable et gris",
    palette: "crème sable gris apaisé",
    description: "Petit format raffiné, parfait pour une entrée, une chambre ou un coin lecture.",
    descriptionLong: "Ce format plus accessible peut aussi servir de porte d'entrée pour de nouveaux collectionneurs. Il offre une belle présence sans dominer l'espace.",
    featured: false,
    stripeUrl: ""
  }
];
